### ISSUE TITLE
"Syntax error near this location" on line 84 character 2432 on errie doc straight after install

### ISSUE THREAD

**Issue by halloleo** [AlesTsurko/eerie#35]
I have just installed Eerie (separately, because I installed Io without Eerie).

When I run

    eerie doc

I get "_Error: compile error: "Syntax error near this location" on line 84 character 2432_" nothing else.

Here my environment:

* PATH looks like:
    
        /opt/local/bin   # path to io
        ...
        /home/me/.eerie/base/bin
        /home/me/.eerie/activeEnv/bin
        ...

* Io executable is in `/opt/local/bin`, Eerie executable is in `/home/me/.eerie/base/bin`.

* System is a CentOS linux. 

What's going on?

**Comment by ales-tsurko** [comment]
Thanks for the report! There're two things, which may cause this problem:

- Eerie from master branch is unstable at the moment
- I've made some changes in Docio and they're incompatible with current version of Eerie

For the first point, go into Io repo, click on Eerie directory there. This way you'll open Eerie repo at the released commit. Install this version.

For the second point, unfortunately there's no way except of waiting for a new Eerie release. It's in active development at the moment and be ready very soon.

Documentation may not work because of Docio package, but everything else like installing and updating packages should work. The current version of Eerie can't install a specific version of a package (this is not a problem anymore in the new version). This is why we get what we get...

**Comment by halloleo** [comment]
Thank for your reply.

_To your first point:_ I installed eerie from `git clone https://github.com/IoLanguage/eerie.git`. So you are saying I should clone not the latest master commit? Which one? 

_To your 2nd point:_ The docio issues should only affect the "doc' task (`eerie doc`), right? So I still can use it to install other addons?

**Comment by ales-tsurko** [comment]
> To your first point: I installed eerie from git clone https://github.com/IoLanguage/eerie.git. So you are saying I should clone not the latest master commit? Which one?

Remove installed version of eerie (`rm -rf /home/me/.eerie`), do `git checkout 882524741a` in your local eerie repo, then install.

> To your 2nd point: The docio issues should only affect the "doc' task (eerie doc), right? So I still can use it to install other addons?

Yes.

**Comment by halloleo** [comment]
Thanks for the hand-holding! :-) Installing via eerie seems to work now.
